### ISSUE TITLE
Plugin does throw error

### ISSUE THREAD

**Issue by palass1234** [getbowtied/shopkeeper-portfolio#1]
I use the shopkeeper theme (bought on theme forrest) and therefore the portfolio plugin, too. 

Everything worked fine, but starting this week the following error shows on my shoppage/portfolio: 

Warning: count(): Parameter must be an array or an object that implements Countable in /home/redperch/public_html/shop/wp-content/plugins/shopkeeper-portfolio-master/includes/shortcodes/wp/portfolio.php on line 50

The code in question looks like this: 

`if ( count($portfolio_categories_queried) > 0 ) :`

Since I am not a developer, I am a little bit lost. 

Best regards.

**Comment by rthvanesa** [comment]
Hello @palass1234 ,

We are sorry for the inconvenience. We have applied a fix and released Shopkeeper Portfolio Addon 1.3.3.

Please update the plugin and let me know if you encounter any other issues.

Have a good one!
