### ISSUE TITLE
Create way to update `portfolio-category`

### ISSUE THREAD

**Issue by pedroapfilho** [getbowtied/shopkeeper-portfolio#2]
Currently, we can only change the `portfolio-item`, but we can't change the `portfolio-category`. Could you please allow this option, or provide a snippet to do so?

**Comment by rthvanesa** [comment]
Hi @pedroapfilho,

We took your request into consideration and will work on introducing a new option for the taxonomy slug in the next plugin update.

Thank you for using the plugin.
Have a great day!

**Comment by rthvanesa** [comment]
Hi @pedroapfilho,

I'm just writing to let you know we have included a new customizer option in our latest plugin update. You should be able to change the category slug easily now. 
Please update the plugin and let me know if you encounter any issues.

Thank you for using out products.
Have a great day!
